project_name: webhookdb
builds:
  - id: distrib
    ldflags:
      - -s -w -X github.com/lithictech/webhookdb-cli/config.Version={{.Version}} -X github.com/lithictech/webhookdb-cli/config.BuildSha={{.Commit}} -X github.com/lithictech/webhookdb-cli/config.BuildTime={{.Date}}
    binary: webhookdb
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
  - id: wasm
    ldflags:
      - -s -w -X github.com/lithictech/webhookdb-cli/config.Version={{.Version}} -X github.com/lithictech/webhookdb-cli/config.BuildSha={{.Commit}} -X github.com/lithictech/webhookdb-cli/config.BuildTime={{.Date}}
    binary: webhookdb
    targets:
      - js_wasm
archives:
  - id: distrib
    builds:
      - distrib
    files:
      - match-nothing-to-keep-archive-binary-only*
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "darwin" }}macos
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
  - id: wasm
    builds:
      - wasm
    format: binary
checksum:
  name_template: 'checksums.txt'
  ids:
    - distrib
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: checksum
release:
  ids:
    - distrib
  draft: true
blobs:
  - provider: s3
    ids:
      - wasm
    bucket: static.webhookdb.com
    region: us-west-2
    folder: "webhookdb-cli/{{.Version}}"
brews:
  - repository:
      owner: lithictech
      name: homebrew-webhookdb
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: next
    ids:
      - distrib
    commit_author:
      name: webhookdbreleaser
      email: webhookdb@lithic.tech
    description: "Query and store any API in real-time with SQL. More at https://webhookdb.com"
    homepage: "https://webhookdb.com"
    caveats: "❤ Thanks for installing the WebhookDB CLI! Run `webhookdb auth login` to get register or sign in."
