builds:
  - binary: webhookdb
    id: webhookdb
    goos:
      - linux
      - windows
    goarch:
      - amd64
  # We need separated builds for MacOS binaries so we can notarize them.
  - binary: webhookdb
    id: webhookdb-macos-amd64
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon -log-level debug gon-amd64.hcl
  - binary: webhookdb
    id: webhookdb-macos-arm64
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post: gon -log-level debug gon-arm64.hcl
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: checksum
