name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write # Needed to create a release

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: --debug release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needs write access to webhookdb-cli contents
          TAP_GITHUB_TOKEN: ${{ secrets.BREWTAPS_GITHUB_TOKEN }} # Needs write access to homebrew-webhookdb-cli contents (and PRs?)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Needs write access to S3
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
